name: task_list_app
description: A simple task list app with Firebase.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.8  # Adicione esta linha com a indentação correta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true